apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: redis
spec:
  selector:
    app: redis
  ports:
    - name: metrics
      port: 59121
      targetPort: 59121
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.29.0
        args:
        - "--redis.addr=redis-i2.redis.svc.cluster.local:6379"
        ports:
        - containerPort: 59121

